spring:
  profiles:
    active: dev

  application:
    name: bank-system


  flyway:
    enabled: true
    baseline-on-migrate: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: off